package coordination

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

func readConfigError(t *testing.T, base string, id RunID) ConfigErrorRecord {
	t.Helper()
	raw, err := os.ReadFile(configErrorPath(base, id))
	if err != nil {
		t.Fatalf("read config-error.json: %v", err)
	}
	var rec ConfigErrorRecord
	if err := json.Unmarshal(raw, &rec); err != nil {
		t.Fatalf("decode config-error.json: %v", err)
	}
	return rec
}

func TestWriteConfigErrorRecordsTheDistinctionTheExitCodeCannotCarry(t *testing.T) {
	base := secureTempDir(t)

	diag := "GO_SPECS_RUN_TOKEN is missing; it is generated by the preflight step"
	if err := WriteConfigError(base, "run-1", "example.com/m/calc", ReasonMissingRunToken, diag); err != nil {
		t.Fatalf("WriteConfigError: %v", err)
	}

	rec := readConfigError(t, base, "run-1")
	if rec.SchemaVersion == "" {
		t.Fatal("the record carries no schema version")
	}
	if rec.RunID != "run-1" || rec.PackagePath != "example.com/m/calc" {
		t.Fatalf("record identity = %q / %q", rec.RunID, rec.PackagePath)
	}
	if rec.Reason != ReasonMissingRunToken {
		t.Fatalf("Reason = %q, want a machine-readable cause finalize can branch on", rec.Reason)
	}
	if rec.Diagnostic != diag {
		t.Fatalf("Diagnostic = %q", rec.Diagnostic)
	}
	if rec.ObservedAt.IsZero() {
		t.Fatal("ObservedAt is zero")
	}
	if mode := modeOf(t, configErrorPath(base, "run-1")); mode != 0o600 {
		t.Fatalf("config-error.json mode = %04o, want 0600", mode)
	}
}

func TestWriteConfigErrorIsFirstWriterWins(t *testing.T) {
	// Every package in the invocation observes the same misconfiguration. The first account of it
	// is as good as the tenth, so a second failing package must neither overwrite the record nor
	// report an error on that account (contract v1.2.6 §5).
	base := secureTempDir(t)

	if err := WriteConfigError(base, "run-1", "pkg/a", ReasonMissingRunToken, "first"); err != nil {
		t.Fatalf("first WriteConfigError: %v", err)
	}
	if err := WriteConfigError(base, "run-1", "pkg/b", ReasonInvalidRunID, "second"); err != nil {
		t.Fatalf("a second failing package reported an error it should have absorbed: %v", err)
	}

	rec := readConfigError(t, base, "run-1")
	if rec.PackagePath != "pkg/a" || rec.Diagnostic != "first" {
		t.Fatalf("the first record was overwritten: %+v", rec)
	}
}

func TestWriteConfigErrorNeverRecordsTheToken(t *testing.T) {
	base := secureTempDir(t)
	if err := WriteConfigError(base, "run-1", "pkg/a", ReasonInvalidRunToken, "token rejected"); err != nil {
		t.Fatal(err)
	}
	raw, err := os.ReadFile(configErrorPath(base, "run-1"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), validToken) {
		t.Fatalf("config-error.json contains a token:\n%s", raw)
	}
}

func TestWriteConfigErrorRejectsAnUnsafeRunID(t *testing.T) {
	base := secureTempDir(t)
	if err := WriteConfigError(base, "../escape", "pkg/a", ReasonInvalidRunID, "x"); err == nil {
		t.Fatal("WriteConfigError accepted a traversal run id")
	}
}
